import logging

try:
    # __version__ is generated by versioningit at build time.  When running
    # from a source checkout without invoking the build system, this file may
    # be missing, so fall back to a placeholder version string.
    from ._version import __version__
except Exception:
    __version__ = "0+unknown"
from .info import __packagename__

__all__ = ["__packagename__", "__version__"]

lgr = logging.getLogger(__name__)
lgr.debug("Starting the abomination")  # just to "run-test" logging
